### ISSUE TITLE
Step 2 of Directions GitHub hyperlink dead link 404

### ISSUE THREAD

**Issue by ghost** [amazon-connect/voice-of-the-customer-integrations#3]
Seeking advice with GitHub hyper link in Step 2. This link used to route to: https://github.com/aws-quickstart/quickstart-connect-voci however now returns 404. 

Is this step to take all the files zipped into lambda and dump them into S3? Further clarification needed, please help. Thank you. 

Reference: 
2. Create an S3 bucket with a top level folder and copy all files into it from GitHub

aws s3 mb s3://my-unique-bucket
aws s3 sync . s3://my-unique-bucket/ --acl public-read

**Comment by efh365** [comment]
Thanks for pointing out the broken link. This project was moved from that old location so the link should point to this project instead. You should just take all files from this repo and copy them to your bucket
