### ISSUE TITLE
Agent key phrases, customer key phrases, agent and customer sentiment - no display

### ISSUE THREAD

**Issue by angelica-celis** [amazon-connect/voice-of-the-customer-integrations#4]
Hi all,

I hope all is well. I'm hoping you can help me with this. We're encountering issues while implementing the voice of the customer integrations with our amazon connect instance. We're not able to get any result on the dashboard on Kibana of the Agent Key Phrases, Customer Key Phrases, and AgentAndCustomerSentiment. We only got the result Total Incoming Calls, Agents Logged in, etc. Although we followed the instruction clearly, from the first step until the last step, we are still not getting any results after we talked to an agent. Would you happen to know why? 

Please see the attached images for your references: 

![image](https://user-images.githubusercontent.com/43126150/86031332-4712c900-ba68-11ea-8423-18e75fdbea81.png)
![image](https://user-images.githubusercontent.com/43126150/86031368-5134c780-ba68-11ea-8a40-0e6eadbd754e.png)

Thank you,

**Comment by efh365** [comment]
Hi. It looks like calls are making it to the dashboard, but the AI related output is not. Can you check whether transcription jobs are being triggered once the call recording is placed in the S3 bucket? 

You can see here that when an object is placed in the S3 bucket it kicks off the transcription event. So you should check the step function console to see if there are any functions going or if there are any failures. https://github.com/amazon-connect/voice-of-the-customer-integrations/blob/master/templates/quickstart-connect-voci-base-pipeline.yaml#L288

**Comment by efh365** [comment]
@angelica-celis do you still need help here?
